name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install -y cmake libzmq3-dev

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Rust cache
        uses: Swatinem/rust-cache@v1.3.0

      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --all-targets --all-features --no-fail-fast --verbose
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off'

      - id: coverage
        name: Generate coverage
        uses: actions-rs/grcov@v0.1.6

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ${{ steps.coverage.outputs.report }}
          directory: ./coverage/reports/

  functional-test:
    name: Functional tests
    strategy:
      matrix:
        test: [
          bitcoin,
          monero,
        ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install -y cmake libzmq3-dev docker-compose

      - name: Compose docker services
        run: cd tests && docker-compose up -d

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Correct permissions
        run: sudo chown -R $USER tests

      - name: Rust cache
        uses: Swatinem/rust-cache@v1.3.0
        with:
          key: test-${{ matrix.test }}

      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --tests ${{ matrix.test }} --workspace --all-targets --all-features --no-fail-fast --verbose -- --ignored --test-threads=1
